### ISSUE TITLE
Error message for item

### ISSUE THREAD

**Issue by TheAffront** [evepraisal/go-evepraisal#103]
The following item cannot be found using the add-in script on Google Sheets but it does appear if you use the Evepraisal website.

R.A.M.- Armor/Hull Tech

This is the error that is shown in Google sheets:

![Lookup Error](https://user-images.githubusercontent.com/51953875/60104747-f92efb00-9759-11e9-8e84-a845dd8be76c.jpg)

**Comment by ericvolp12** [comment]
You need to use the item ID in order to use the spreadsheet script. The ID of that item is `11475`, so use that in the sheet formula instead and you should have no issues. To find item IDs, you can click on them in Evepraisal and you'll be redirected to their pages like this - https://evepraisal.com/item/11475

You can then see in the URL what the ID is.

**Comment by TheAffront** [comment]
Thank you for your help in this matter. The reason I posted the error is because every other R.A.M. item (and for that matter every item period) works perfectly in my spreadsheet, only this one brings up an error that's why I thought I would report it.

**Comment by ericvolp12** [comment]
Ah, I'd assume it has something to do with the forward slash in the item
name, though it looks like it's being properly escaped when parsed into a
URL.

**Comment by TheAffront** [comment]
Yes, the URL works perfectly but for some reason (as yet unknown) I get that error message in my spreadsheet. I wonder if the forward slash is the problem but I'm no pro using google sheets to see how to fix it.

**Comment by sudorandom** [comment]
I figured out this weird edge case and deployed the fix!

https://evepraisal.com/item/R.A.M.-%20Armor%2FHull%20Tech.json
