### ISSUE TITLE
Unknown Format

### ISSUE THREAD

**Issue by FABNACHTEN** [evepraisal/go-evepraisal#127]
Appraisal with the format: evepraisal.com/a/qlpbp

Describe the format (where you got it, etc)

**Comment by webwizrd** [comment]
If you open the result page and go to "export>JSON", you will see a section in the JSON labelled "raw", which is the original pasted text before parsing:

`"raw":"Chiral Structures*\t8’865\tGrundlegende Güter – Rang 1*\tPlanetarische Güter*\t\r\nPlasmoids...`

As you can see, some of the text is in German, which is why EP has difficulty parsing that part and complains, I guess.

**Comment by sudorandom** [comment]
A fix for this has been released.
