### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by Rayvenhaus** [evepraisal/go-evepraisal#27]
Are there installation instructions for this version?

**Comment by raykai** [comment]
im looking for that too!

**Comment by Rayvenhaus** [comment]
So, I assume that this is YAAEP?  (Yet Another Abandoned Eve Project)

**Comment by sudorandom** [comment]
This is a server-side tool, meaning that its primary use-case is to be the code that powers evepraisal.com. I'm hosting the code publicly so that others can re-host the site if I get hit by a bus or something.

There a couple reasons I haven't responded to this particular post yet:

1. I've just not done the packaging required to make the install process painless for people who aren't familiar with go. I've been meaning to do that but since it's so far away from the purpose of this repo that I'd spend the rare moment that I have to work on this project adding features instead.
2. I'm not really sure where you're coming from in terms of experience. I've only run this on linux and OSX so I can't guarantee that it will even halfway work on Windows. Are you looking for just hosting it locally for only you to mess around with or are you intending to host a clone of evepraisal with a different URL? I'm totally cool with people doing either. I know there are a couple clones that use the older python-based code. Again, however, this use-case isn't the primary goal of this project.

And to address your last comment, no, this project is not dead. I'd hope you can see that by the fact that there's been recent feature additions to evepraisal as recent as 3 days ago. Here are very crude, untested instructions. Again, I don't know if you want to host this just for yourself or to be a 'production' system so there's some notes for both but it's far from comprehensive.

## Getting it to run
1. Install go
2. Checkout the repo into your GOPATH (assumes that gopath is set)
```
git clone https://github.com/evepraisal/go-evepraisal.git $GOPATH/src/github.com/evepraisal/go-evepraisal
cd $GOPATH/src/github.com/evepraisal/go-evepraisal
```
3. Download dependencies:
```
make setup
```
4. Run it in a non-production way 
```
make run
```

## Production Server
This is what I have documented for setting up a new evepraisal server. My notes have significantly more setup but those parts are centered around security and ensuring backups:
```
useradd -r evepraisal
mkdir /etc/evepraisal
mkdir /usr/local/evepraisal
mkdir /usr/local/evepraisal/db
chown -R evepraisal:evepraisal /usr/local/evepraisal
```

After that, I just run `make deploy-prod` which will builds the binary file (specifically for 64-bit linux because I develop on a mac) and then runs `./scripts/deploy.sh` with a couple environment variables. This script uploads the systemd service file and copies the binary file up to the server and then restarts the service.

**Comment by Rayvenhaus** [comment]
Thank you very much

**Comment by Traace** [comment]
make deploy-prod doesn't work on my vanilla install.

` running "/usr/share/go/1.9/contrib/bin/go-bindata": fork/exec /usr/share/go/1.9/contrib/bin/go-bindata: no such file or directory`

I have go-bindata installed... don't know whats wrong

Should I open another issue?

**Comment by sudorandom** [comment]
@Traace I changed the makefile to not require supporting binaries to live in $GOPATH. Pull from master and that should work for you now.
