### ISSUE TITLE
Error writing out vendor tree for fsnotify.v1 on make setup

### ISSUE THREAD

**Issue by jdrc** [evepraisal/go-evepraisal#65]
When running make setup the manifest gets to dep ensure and produces the below error.
Any idea what I might be doing wrong?

```

grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export gopkg.in/fsnotify.v1: fatal: failed to unpack tree object c2828203cd70a50dcccfb2761f8b1f8ceef9a8e9
: exit status 128
Makefile:21: recipe for target 'setup' failed
make: *** [setup] Error 1
```

**Comment by sudorandom** [comment]
That's odd. What version of dep and go do you have at the moment? I made a change in master that will install the latest released version of dep instead of potentially unverified changes from just pulling it from master... so maybe try again now? You might have been unlucky and gotten a buggy version of dep.

**Comment by sudorandom** [comment]
I'm closing this issue. Feel free to open the issue again if you're still having the issue after updating.
