### ISSUE TITLE
ISK values are rounded in the single sell and buy values

### ISSUE THREAD

**Issue by jonah-walker** [evepraisal/go-evepraisal#8]
The value is now rounded as seen here: http://evepraisal.com/a/bx68v

**Comment by sudorandom** [comment]
@jonah-walker It was actually intended to make the numbers easier to read and because the values are estimates anyway... however, as you see, with small values (like a single unit of tritanium) the rounding can be significant.

I changed it so that values under 10,000 will have two decimal places. Hopefully this is less confusing for the case that you pointed out!

Thanks for opening an issue!
