### ISSUE TITLE
Evepraisal Rate Limit

### ISSUE THREAD

**Issue by xyx0826** [evepraisal/go-evepraisal#82]
Hi,

First of all, thank you very much for this wonderful tool.

I am the developer of [Priceall](https://github.com/xyx0826/Priceall), a tool using Evepraisal API to do quick item pricings from clipboard. It is triggered by a hotkey.

I'm thinking of adding automatic checking, that is, to request an appraisal check as soon as clipboard text changes - without needing to press the hotkey.

The problem is, people may copy all sort of stuff into the clipboard that is not necessarily EVE-related.  Would this put too much stress on the servers? I'd like to hear your advice before going ahead. Thank you.

*P.S. Priceall User-Agent can be identified by* `Priceall/{appVersion} (Github.com/xyx0826/Priceall)`

**Comment by sudorandom** [comment]
Thanks for reaching out and also thanks for using such an explicit user-agent!

I think the biggest issue that would come up when using this is causing too many persistent appraisals. I browsed the code a little bit and it looks like it doesn't persist. This might be for the best to avoid privacy issues. Based on the requests that I see coming in you pass in `persist=no` properly so that's not a concern.

The other concern is that just the CPU that it takes to parse out the text and will add up... and I'm just not sure if that's going to be a problem.

I'd say go for it and if there's any issues I can reach out to you.
